teams = [
    '0',
    'Arsenal',
    'Aston Villa',
    'Bournemouth',
    'Brentford',
    'Brighton',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Ipswich',
    'Leicester',
    'Liverpool',
    'Man City',
    'Man Utd',
    'Newcastle',
    'Nott\'m Forest',
    'Southampton',
    'Spurs',
    'West Ham',
    'Wolves'
]
teams_u = [
    {'title':'0','uid':-1},
    {'title':'Arsenal','uid': '83'},
    {'title':'Aston Villa','uid':'71'},
    {'title':'Bournemouth','uid':'-1'},
    {'title':'Brentford','uid':'244'},
    {'title':'Brighton','uid':'220'},
    {'title':'Burnley','uid':'-1'},
    {'title':'Chelsea', 'uid':'80'},
    {'title':'Crystal Palace','uid':'78'},
    {'title':'Everton','uid':'72'},
    {'title':'Fulham','uid':'-1'},
    {'title':'Liverpool','uid':'87'},
    {'title':'Luton Town','uid':'-1'},
    {'title':'Manchester City','uid':'88'},
    {'title':'Manchester United','uid':'89'},
    {'title':'Newcastle United','uid':'86'},
    {'title':'Nottingham Forest','uid':'-1'},
    {'title':'Sheffield United','uid':'-1'},
    {'title':'Tottenham','uid':'82'},
    {'title':'West Ham', 'uid':'81'},
    {'title':'Wolverhampton Wanderers','uid':'229'},
]

colors = {
    'Arsenal':'#EF0107',
    'Aston Villa':'#95BFE5',
    'Brighton':'#005daa',
    'Bournemouth':'#DA291C',
    'Brentford':'#e30613',
    'Burnley':'#6C1D45',
    'Chelsea':'#034694',
    'Crystal Palace':'#1b458f',
    'Everton':'#274488',
    'Fulham':'#ffffff',
    'Liverpool':'#d01317',
    'Luton':'#FFFFFF',
    'Man City':'#6CADDF',
    'Man Utd':'#da020e',
    'Newcastle':'#000000',
    'Nott\'m Forest':"#e53233",
    'Sheffield Utd':'#EE2737',
    'Spurs':'#ffffff',
    'West Ham':'#7c2c3b',
    'Wolves':'#FDB913',
    'Ipswich':'#0E00F7',
    'Southampton':'#D71920',
    'Leicester':'#003090'
}